version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://api.local:3000
    networks:
      - app-network

  backend:
    build:
      context: ./golang-auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GIN_MODE=release
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
